import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function WhiteBox() {
  return (
    <div className="bg-white rounded-lg shadow-lg p-4">
      <h1 className="text-2xl font-semibold text-gray-900">Hello World</h1>
      <p className="text-gray-700">
        Lorem ipsum dolor sit amet, consectetur adipisicing elit.
      </p>
    </div>
  );
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={inter.className}
        style={{
          background: "white",
        }}
      >
        {children}
      </body>
    </html>
  );
}
