export const candidates11 = [
  {
    id: 1,
    name: "햄버거",
    imageUrl: "https://source.unsplash.com/1600x900/?burger",
  },
  {
    id: 2,
    name: "볶음밥",
    imageUrl: "https://source.unsplash.com/1600x900/?friedrice",
  },
  {
    id: 3,
    name: "파스타",
    imageUrl: "https://source.unsplash.com/1600x900/?pasta",
  },
  {
    id: 4,
    name: "라면",
    imageUrl: "https://source.unsplash.com/1600x900/?ramen",
  },
];

// 200명 후보자
export const candidates = [
  { id: 1, name: "후보자 1", imageUrl: "https://via.placeholder.com/150" },
  { id: 2, name: "후보자 2", imageUrl: "https://via.placeholder.com/150" },
  { id: 3, name: "후보자 3", imageUrl: "https://via.placeholder.com/150" },
  { id: 4, name: "후보자 4", imageUrl: "https://via.placeholder.com/150" },
  { id: 5, name: "후보자 5", imageUrl: "https://via.placeholder.com/150" },
  { id: 6, name: "후보자 6", imageUrl: "https://via.placeholder.com/150" },
  { id: 7, name: "후보자 7", imageUrl: "https://via.placeholder.com/150" },
  { id: 8, name: "후보자 8", imageUrl: "https://via.placeholder.com/150" },
  { id: 8, name: "후보자 8", imageUrl: "https://via.placeholder.com/150" },
  { id: 8, name: "후보자 8", imageUrl: "https://via.placeholder.com/150" },
  { id: 8, name: "후보자 8", imageUrl: "https://via.placeholder.com/150" },
  { id: 8, name: "후보자 8", imageUrl: "https://via.placeholder.com/150" },
  { id: 8, name: "후보자 8", imageUrl: "https://via.placeholder.com/150" },
  { id: 8, name: "후보자 8", imageUrl: "https://via.placeholder.com/150" },
  { id: 8, name: "후보자 8", imageUrl: "https://via.placeholder.com/150" },
  { id: 8, name: "후보자 8", imageUrl: "https://via.placeholder.com/150" },
  { id: 8, name: "후보자 8", imageUrl: "https://via.placeholder.com/150" },
  { id: 8, name: "후보자 8", imageUrl: "https://via.placeholder.com/150" },
  { id: 8, name: "후보자 8", imageUrl: "https://via.placeholder.com/150" },
  { id: 8, name: "후보자 8", imageUrl: "https://via.placeholder.com/150" },
  { id: 8, name: "후보자 8", imageUrl: "https://via.placeholder.com/150" },
  { id: 8, name: "후보자 8", imageUrl: "https://via.placeholder.com/150" },
  { id: 8, name: "후보자 8", imageUrl: "https://via.placeholder.com/150" },
  { id: 8, name: "후보자 8", imageUrl: "https://via.placeholder.com/150" },
  { id: 8, name: "후보자 8", imageUrl: "https://via.placeholder.com/150" },
  { id: 8, name: "후보자 8", imageUrl: "https://via.placeholder.com/150" },
  { id: 8, name: "후보자 8", imageUrl: "https://via.placeholder.com/150" },
  { id: 8, name: "후보자 8", imageUrl: "https://via.placeholder.com/150" },
  { id: 8, name: "후보자 8", imageUrl: "https://via.placeholder.com/150" },
  { id: 8, name: "후보자 8", imageUrl: "https://via.placeholder.com/150" },
  { id: 8, name: "후보자 8", imageUrl: "https://via.placeholder.com/150" },
  { id: 8, name: "후보자 8", imageUrl: "https://via.placeholder.com/150" },
  { id: 8, name: "후보자 8", imageUrl: "https://via.placeholder.com/150" },
  { id: 8, name: "후보자 8", imageUrl: "https://via.placeholder.com/150" },
  { id: 8, name: "후보자 8", imageUrl: "https://via.placeholder.com/150" },
  { id: 8, name: "후보자 8", imageUrl: "https://via.placeholder.com/150" },
  { id: 8, name: "후보자 8", imageUrl: "https://via.placeholder.com/150" },
  { id: 8, name: "후보자 8", imageUrl: "https://via.placeholder.com/150" },
  { id: 8, name: "후보자 8", imageUrl: "https://via.placeholder.com/150" },
  { id: 8, name: "후보자 8", imageUrl: "https://via.placeholder.com/150" },
  { id: 8, name: "후보자 8", imageUrl: "https://via.placeholder.com/150" },
  { id: 8, name: "후보자 8", imageUrl: "https://via.placeholder.com/150" },
  { id: 8, name: "후보자 8", imageUrl: "https://via.placeholder.com/150" },
  { id: 8, name: "후보자 8", imageUrl: "https://via.placeholder.com/150" },
  { id: 8, name: "후보자 8", imageUrl: "https://via.placeholder.com/150" },
  { id: 8, name: "후보자 8", imageUrl: "https://via.placeholder.com/150" },
  { id: 8, name: "후보자 8", imageUrl: "https://via.placeholder.com/150" },
  { id: 8, name: "후보자 8", imageUrl: "https://via.placeholder.com/150" },
  { id: 8, name: "후보자 8", imageUrl: "https://via.placeholder.com/150" },
  { id: 8, name: "후보자 8", imageUrl: "https://via.placeholder.com/150" },
  { id: 8, name: "후보자 8", imageUrl: "https://via.placeholder.com/150" },
  { id: 8, name: "후보자 8", imageUrl: "https://via.placeholder.com/150" },
  { id: 8, name: "후보자 8", imageUrl: "https://via.placeholder.com/150" },
  { id: 8, name: "후보자 8", imageUrl: "https://via.placeholder.com/150" },
  { id: 8, name: "후보자 8", imageUrl: "https://via.placeholder.com/150" },
  { id: 8, name: "후보자 8", imageUrl: "https://via.placeholder.com/150" },
  { id: 8, name: "후보자 8", imageUrl: "https://via.placeholder.com/150" },
  { id: 8, name: "후보자 8", imageUrl: "https://via.placeholder.com/150" },
  { id: 8, name: "후보자 8", imageUrl: "https://via.placeholder.com/150" },
  { id: 8, name: "후보자 8", imageUrl: "https://via.placeholder.com/150" },
  { id: 8, name: "후보자 8", imageUrl: "https://via.placeholder.com/150" },
  { id: 8, name: "후보자 8", imageUrl: "https://via.placeholder.com/150" },
  { id: 8, name: "후보자 8", imageUrl: "https://via.placeholder.com/150" },
  { id: 8, name: "후보자 8", imageUrl: "https://via.placeholder.com/150" },
  { id: 8, name: "후보자 8", imageUrl: "https://via.placeholder.com/150" },
  { id: 8, name: "후보자 8", imageUrl: "https://via.placeholder.com/150" },
  { id: 8, name: "후보자 8", imageUrl: "https://via.placeholder.com/150" },
  { id: 8, name: "후보자 8", imageUrl: "https://via.placeholder.com/150" },
  { id: 8, name: "후보자 8", imageUrl: "https://via.placeholder.com/150" },
  { id: 8, name: "후보자 8", imageUrl: "https://via.placeholder.com/150" },
  { id: 8, name: "후보자 8", imageUrl: "https://via.placeholder.com/150" },
  { id: 8, name: "후보자 8", imageUrl: "https://via.placeholder.com/150" },
  { id: 8, name: "후보자 8", imageUrl: "https://via.placeholder.com/150" },
  { id: 8, name: "후보자 8", imageUrl: "https://via.placeholder.com/150" },
  { id: 8, name: "후보자 8", imageUrl: "https://via.placeholder.com/150" },
  { id: 8, name: "후보자 8", imageUrl: "https://via.placeholder.com/150" },
  { id: 8, name: "후보자 8", imageUrl: "https://via.placeholder.com/150" },
  { id: 8, name: "후보자 8", imageUrl: "https://via.placeholder.com/150" },
  { id: 8, name: "후보자 8", imageUrl: "https://via.placeholder.com/150" },
  { id: 8, name: "후보자 8", imageUrl: "https://via.placeholder.com/150" },
  { id: 8, name: "후보자 8", imageUrl: "https://via.placeholder.com/150" },
  { id: 8, name: "후보자 8", imageUrl: "https://via.placeholder.com/150" },
  { id: 8, name: "후보자 8", imageUrl: "https://via.placeholder.com/150" },
  { id: 8, name: "후보자 8", imageUrl: "https://via.placeholder.com/150" },
  { id: 8, name: "후보자 8", imageUrl: "https://via.placeholder.com/150" },
  { id: 8, name: "후보자 8", imageUrl: "https://via.placeholder.com/150" },
  { id: 8, name: "후보자 8", imageUrl: "https://via.placeholder.com/150" },
  { id: 8, name: "후보자 8", imageUrl: "https://via.placeholder.com/150" },
  { id: 8, name: "후보자 8", imageUrl: "https://via.placeholder.com/150" },
  { id: 8, name: "후보자 8", imageUrl: "https://via.placeholder.com/150" },
  { id: 8, name: "후보자 8", imageUrl: "https://via.placeholder.com/150" },
  { id: 8, name: "후보자 8", imageUrl: "https://via.placeholder.com/150" },
  { id: 8, name: "후보자 8", imageUrl: "https://via.placeholder.com/150" },
  { id: 8, name: "후보자 8", imageUrl: "https://via.placeholder.com/150" },
  { id: 8, name: "후보자 8", imageUrl: "https://via.placeholder.com/150" },
  { id: 8, name: "후보자 8", imageUrl: "https://via.placeholder.com/150" },
  { id: 8, name: "후보자 8", imageUrl: "https://via.placeholder.com/150" },
  { id: 8, name: "후보자 8", imageUrl: "https://via.placeholder.com/150" },
  { id: 8, name: "후보자 8", imageUrl: "https://via.placeholder.com/150" },
  { id: 8, name: "후보자 8", imageUrl: "https://via.placeholder.com/150" },
  { id: 8, name: "후보자 8", imageUrl: "https://via.placeholder.com/150" },
  { id: 8, name: "후보자 8", imageUrl: "https://via.placeholder.com/150" },
  { id: 8, name: "후보자 8", imageUrl: "https://via.placeholder.com/150" },
  { id: 8, name: "후보자 8", imageUrl: "https://via.placeholder.com/150" },
  { id: 8, name: "후보자 8", imageUrl: "https://via.placeholder.com/150" },
  { id: 8, name: "후보자 8", imageUrl: "https://via.placeholder.com/150" },
  { id: 8, name: "후보자 8", imageUrl: "https://via.placeholder.com/150" },
  { id: 8, name: "후보자 8", imageUrl: "https://via.placeholder.com/150" },
  { id: 8, name: "후보자 8", imageUrl: "https://via.placeholder.com/150" },
  { id: 8, name: "후보자 8", imageUrl: "https://via.placeholder.com/150" },
  { id: 8, name: "후보자 8", imageUrl: "https://via.placeholder.com/150" },
  { id: 8, name: "후보자 8", imageUrl: "https://via.placeholder.com/150" },
  { id: 8, name: "후보자 8", imageUrl: "https://via.placeholder.com/150" },
  { id: 8, name: "후보자 8", imageUrl: "https://via.placeholder.com/150" },
  { id: 8, name: "후보자 8", imageUrl: "https://via.placeholder.com/150" },
  { id: 8, name: "후보자 8", imageUrl: "https://via.placeholder.com/150" },
  { id: 8, name: "후보자 8", imageUrl: "https://via.placeholder.com/150" },
  { id: 8, name: "후보자 8", imageUrl: "https://via.placeholder.com/150" },
  { id: 8, name: "후보자 8", imageUrl: "https://via.placeholder.com/150" },
  { id: 8, name: "후보자 8", imageUrl: "https://via.placeholder.com/150" },
  { id: 8, name: "후보자 8", imageUrl: "https://via.placeholder.com/150" },
  { id: 8, name: "후보자 8", imageUrl: "https://via.placeholder.com/150" },

  // ... 추가 후보자
];
